# Generated by Django 5.1.2 on 2024-11-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=150)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="blog_images/", verbose_name="Изображение"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField()),
            ],
            options={
                "verbose_name": "запись в блоге",
                "verbose_name_plural": "запись в блоге",
                "ordering": ["created_at"],
            },
        ),
    ]
