# Generated by Django 5.1.2 on 2024-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_views_counter_alter_blog_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовать"),
        ),
    ]
