# Generated by Django 5.1.2 on 2024-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
