# Generated by Django 5.1.2 on 2024-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_category_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="check_box",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(help_text="(укажите цену)", verbose_name="Цена"),
        ),
    ]
