# Generated by Django 5.1.2 on 2024-11-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_check_box_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="check_box",
        ),
        migrations.AddField(
            model_name="product",
            name="checkbox",
            field=models.BooleanField(
                default=False, verbose_name="Согласен с условиями использования сайта"
            ),
        ),
    ]
