# Generated by Django 5.1.2 on 2024-11-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_product_check_box_product_checkbox"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "can_unpublish_product",
                        "Может отменить публикацию продукта в каталоге",
                    ),
                    ("can_delete_product", "Может удалить любой продукта"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="checkbox",
            field=models.BooleanField(
                default=False, verbose_name="Опубликовать продукт в каталоге"
            ),
        ),
    ]
