# Generated by Django 5.1.2 on 2024-11-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("can_unpublish_products", "Can unpublish product")],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
